name: 'Release'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Create tag
        run: git tag ${{ inputs.tag }}

      - name: Push tags
        run: git push origin tag $(git describe --tags --abbrev=0)
